/*
 * This source file was generated by the Gradle 'init' task
 */
package br.edu.fatecpg.restaurante.view;

import br.edu.fatecpg.restaurante.model.*;

public class App {

    public static void main(String[] args) {
        Restaurante restaurante = new Restaurante();

        ItemPedido item1 = new ItemPedido("Hambúrguer Artesanal", 2, 35.50);
        ItemPedido item2 = new ItemPedido("Batata Frita", 1, 15.00);
        ItemPedido item3 = new ItemPedido("Refrigerante", 2, 6.00);
        ItemPedido item4 = new ItemPedido("Pizza Margherita", 1, 45.00);

        Pedido pedido1 = new Pedido(101, 10.00);
        pedido1.adicionarItem(item1);
        pedido1.adicionarItem(item2);
        pedido1.adicionarItem(item3);

        Pedido pedido2 = new Pedido(102, 0.00);
        pedido2.adicionarItem(item4);
        pedido2.adicionarItem(item3);

        pedido2.reservarMesa(5);

        restaurante.adicionarPedido(pedido1);
        restaurante.adicionarPedido(pedido2);

        // Exibindo todos os pedidos
        restaurante.exibirPedidos();

        restaurante.removerPedido(101);
        restaurante.exibirPedidos();
    }
}
