/*
 * This source file was generated by the Gradle 'init' task
 */
package br.edu.fatecpg.passagem.view;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
